default: &default
  adapter: postgresql
  encoding: unicode
  host: ec_db
  port: 5432
  username: root
  password: root

development:
  <<: *default
  database: ec_db

test:
  <<: *default
  database: EC_app_test

production:
  <<: *default
  database: EC_app_production
  username: root
  password: <%= ENV["EC_APP_DATABASE_PASSWORD"] %>
